version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: "Dependencies"
          command: |
            sudo apt-get update -yqq
            sudo apt-get install -yqq gcc
            sudo apt-get install -yqq grub
            sudo apt-get install -yqq nasm
            sudo apt-get install -yqq xorriso
      - run:
          name: "Build"
          command: ./build.sh
