version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: "Dependencies"
          command: |
            apt-get update -yqq
            apt-get install -yqq gcc
            apt-get install -yqq grub
            apt-get install -yqq nasm
            apt-get install -yqq xorriso
      - run:
          name: "Build"
          command: ./build.sh
